id: 1323fb5b599143b1b2616adf58c230cc
initial_creation_type: ocr
source_metadata:
  volumes:
    19c06556dbda41a5b0033b3af4ebff47:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
